//
//  modiferBasicsView.swift
//  SwiftUI prac
//
//  Created by Arihant Marwaha on 23/09/25.
//

import SwiftUI



struct modiferBasicsView: View {
    @State var isviz : Bool = false
    
    var body: some View {
      
        ZStack{
            
            ScrollView{
                VStack(spacing: 20){
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    Color.red
                    Color.blue
                    Color.green
                    Color.orange
                    Color.yellow
                    Color.cyan
                    
                }
            }
            .cornerRadius(300)
            .frame(width: 200, height:200)
            
            
            VStack{
                Text("Arihant")
                    .bold()
                    .italic()
                    .font(.largeTitle)
                    .padding()
                    .offset(x:0,y:0)
                    .frame(width: 200,height: 200)
                    .foregroundStyle(.secondary)
                    .glassEffect(.clear)
                    .onTapGesture {
                        isviz.toggle()
                    }
                
            }
        }
        .padding()
        
        if isviz{
            Button("A new button appears"){
                print("New button clicked")
            }
        
               
        }
        
    }
}

#Preview {
    modiferBasicsView()
}
